#pragma once
#ifndef WAYWARD_SUPPORT_DATETIME_PRIVATE_HPP_INCLUDED
#define WAYWARD_SUPPORT_DATETIME_PRIVATE_HPP_INCLUDED

namespace wayward {
  void set_clock(IClock*);
}

#endif // WAYWARD_SUPPORT_DATETIME_PRIVATE_HPP_INCLUDED
